# # Use the PHP 8.1 runtime
# # runtime: php81

# # # Defaults to "serve index.php" 
# # entrypoint: serve helloworld.php

# runtime: php74
# entrypoint: serve login.php

runtime: php74

handlers:
# Serve php scripts through the router script.
- url: /(.+\.php)$
  script: auto

# Serve all static files directly.
- url: /(.*\.(gif|png|jpg|css|js))$
  static_files: \1
  upload: .*\.(gif|png|jpg|css|js)$

# Serve the index.php file when the root of the domain is requested.
- url: /.*
  script: auto
